mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
tun:
  enable: true
  device: Meta
  stack: system
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 180.76.76.76
    - 119.29.29.29
    - 223.5.5.5
    - 1.2.4.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - https://doh.360.cn/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
  fallback-filter:
    geoip: true
    geoip-code: CN

d: &d  #机场订阅参数
  type: http
  interval: 21600
  health-check:
   enable: true
   url: https://i.ytimg.com/generate_204
   interval: 300

r: &r #分流规则订阅参数
  type: http
  behavior: classical
  interval: 86400

t: &t  #节点测试参数
  url: https://i.ytimg.com/generate_204
  interval: 300
  tolerance: 50

all: &all #所有节点的合集
  use:
    -国内
    -国外

proxies:


proxy-providers:
  
  国内:
    type: http
    url: "https://raw.githubusercontent.com/udontknowho/ml/main/cn"
    path: ./proxy_providers/cn.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  国外:
    type: http
    url: "https://raw.githubusercontent.com/udontknowho/ml/main/airport"
    path: ./proxy_providers/air.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300


proxy-groups:
  - name: DNS
    type: select
    proxies:
      - DIRECT
  - name: Proxy
    type: select
    proxies:
      - DIRECT
      - 免流国外
      - 国外自动
      
  - name: 拦截
    type: select
    proxies:
      - REJECT
      
  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - 国内自动
      - 免流国内

  - name: 免流国内
    type: select
    use:
      - 国内
  - name: 免流国外
    type: select
    use:
      - 国外
  - name: 国内自动
    type: url-test
    use:
      - 国内
  - name: 国外自动
    type: url-test
    use:
      - 国外

  - name: 漏网之鱼
    type: select
    proxies:
      - DIRECT
      - 免流国外
      - 国外自动
      - 国内自动
      - 免流国内
rule-providers:
  IPfake:
    <<: *r
    url: "https://raw.fastgit.org/lwd-temp/anti-ip-attribution/main/generated/rule-provider.yaml"
    path: ./Rules/IPfake.yaml

  BiliBili:
    <<: *r
    url: "https://raw.fastgit.org/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./Rules/bilibili.yaml

  Disney:
    <<: *r
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Disney/Disney.yaml"
    path: ./Rules/Disney.yaml

  Netflix:
    <<: *r
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Netflix/Netflix.yaml
    path: ./Rules/Netflix.yaml

  TikTok:
    <<: *r
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/TikTok/TikTok.yaml"
    path: ./Rules/TikTok.yaml

  YouTube:
    <<: *r
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml"
    path: ./Rules/YouTube.yaml

  Telegram:
    <<: *r
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Telegram/Telegram.yaml"
    path: ./Rules/Telegram.yaml

  Emby:
    <<: *r
    url: "https://raw.fastgit.org/justdoiting/emby-rules/main/Emby.yaml"
    path: ./Rules/Emby.yaml

  Game:
    <<: *r
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Game/Game.yaml"
    path: ./Rules/Game.yaml

  BanEasyPrivacy:
    <<: *r
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Privacy/Privacy_Classical.yaml"
    path: ./Rules/BanEasyPrivacy.yaml

  Advertising:
    <<: *r
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Advertising/Advertising_Classical.yaml
    path: ./Rules/Advertising.yaml

  Download:
    <<: *r
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Download/Download.yaml
    path: ./Rules/Download.yaml

  PrivateTracker:
    <<: *r
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.yaml
    path: ./Rules/PrivateTracker.yaml

  ChinaMax:
    <<: *r
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/ChinaMax/ChinaMax_Classical.yaml
    path: ./Rules/ChinaMax.yaml

  Global:
    <<: *r
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Global/Global_Classical.yaml
    path: ./Rules/Global.yaml

  Lan:
    <<: *r
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script/rule/Clash/Lan/Lan.yaml
    path: ./Rules/Lan.yaml

rules:
  - RULE-SET,BiliBili,Domestic
  - RULE-SET,YouTube,Proxy
  - RULE-SET,Netflix,Proxy
  - RULE-SET,Disney,Proxy
  - RULE-SET,TikTok,Proxy
  - RULE-SET,Emby,Proxy
  - RULE-SET,Telegram,Proxy
  - RULE-SET,Game,Domestic
  - RULE-SET,BanEasyPrivacy,Proxy
  - RULE-SET,Advertising,拦截
  - RULE-SET,Download,Proxy
  - RULE-SET,PrivateTracker,Proxy
  - RULE-SET,IPfake,Domestic
  - RULE-SET,Lan,Proxy
  - GEOIP,CN,Domestic
  - RULE-SET,ChinaMax,Domestic
  - RULE-SET,Global,Proxy
  - MATCH,漏网之鱼